// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ProtoDef.proto
// Protobuf Java Version: 4.30.2

package transportAgency.protobufprotocol;

public final class ProtoDefGenerated {
  private ProtoDefGenerated() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      ProtoDefGenerated.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transportAgency_protobufprotocol_Trip_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_transportAgency_protobufprotocol_Trip_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transportAgency_protobufprotocol_Employee_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_transportAgency_protobufprotocol_Employee_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transportAgency_protobufprotocol_Reservation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_transportAgency_protobufprotocol_Reservation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transportAgency_protobufprotocol_Seat_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_transportAgency_protobufprotocol_Seat_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transportAgency_protobufprotocol_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_transportAgency_protobufprotocol_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transportAgency_protobufprotocol_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_transportAgency_protobufprotocol_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016ProtoDef.proto\022 transportAgency.protob" +
      "ufprotocol\"o\n\004Trip\022\n\n\002id\030\001 \001(\003\022\023\n\013destin" +
      "ation\030\002 \001(\t\022\025\n\rdepartureDate\030\003 \001(\t\022\025\n\rde" +
      "partureTime\030\004 \001(\t\022\030\n\020noSeatsAvailable\030\005 " +
      "\001(\005\".\n\010Employee\022\020\n\010username\030\001 \001(\t\022\020\n\010pas" +
      "sword\030\002 \001(\t\"h\n\013Reservation\022\022\n\nclientName" +
      "\030\001 \001(\t\022\017\n\007noSeats\030\002 \001(\005\0224\n\004trip\030\003 \001(\0132&." +
      "transportAgency.protobufprotocol.Trip\"*\n" +
      "\004Seat\022\016\n\006seatNo\030\001 \001(\005\022\022\n\nclientName\030\002 \001(" +
      "\t\"\217\003\n\007Request\022<\n\004type\030\001 \001(\0162..transportA" +
      "gency.protobufprotocol.Request.Type\0226\n\004t" +
      "rip\030\002 \001(\0132&.transportAgency.protobufprot" +
      "ocol.TripH\000\022>\n\010employee\030\003 \001(\0132*.transpor" +
      "tAgency.protobufprotocol.EmployeeH\000\022D\n\013r" +
      "eservation\030\004 \001(\0132-.transportAgency.proto" +
      "bufprotocol.ReservationH\000\"}\n\004Type\022\013\n\007Unk" +
      "nown\020\000\022\t\n\005Login\020\001\022\n\n\006Logout\020\002\022\r\n\tFindSea" +
      "ts\020\003\022\r\n\tFindTrips\020\004\022\023\n\017MakeReservation\020\005" +
      "\022\020\n\014FindEmployee\020\006\022\014\n\010FindTrip\020\007B\t\n\007payl" +
      "oad\"\371\003\n\010Response\022=\n\004type\030\001 \001(\0162/.transpo" +
      "rtAgency.protobufprotocol.Response.Type\022" +
      "\r\n\005error\030\002 \001(\t\0225\n\005seats\030\003 \003(\0132&.transpor" +
      "tAgency.protobufprotocol.Seat\0225\n\005trips\030\004" +
      " \003(\0132&.transportAgency.protobufprotocol." +
      "Trip\022B\n\013reservation\030\005 \001(\0132-.transportAge" +
      "ncy.protobufprotocol.Reservation\022<\n\010empl" +
      "oyee\030\006 \001(\0132*.transportAgency.protobufpro" +
      "tocol.Employee\0224\n\004trip\030\007 \001(\0132&.transport" +
      "Agency.protobufprotocol.Trip\"y\n\004Type\022\013\n\007" +
      "Unknown\020\000\022\006\n\002Ok\020\001\022\t\n\005Error\020\002\022\r\n\tFindSeat" +
      "s\020\003\022\r\n\tFindTrips\020\004\022\023\n\017MakeReservation\020\005\022" +
      "\020\n\014FindEmployee\020\006\022\014\n\010FindTrip\020\007B7\n trans" +
      "portAgency.protobufprotocolB\021ProtoDefGen" +
      "eratedP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_transportAgency_protobufprotocol_Trip_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_transportAgency_protobufprotocol_Trip_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_transportAgency_protobufprotocol_Trip_descriptor,
        new String[] { "Id", "Destination", "DepartureDate", "DepartureTime", "NoSeatsAvailable", });
    internal_static_transportAgency_protobufprotocol_Employee_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_transportAgency_protobufprotocol_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_transportAgency_protobufprotocol_Employee_descriptor,
        new String[] { "Username", "Password", });
    internal_static_transportAgency_protobufprotocol_Reservation_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_transportAgency_protobufprotocol_Reservation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_transportAgency_protobufprotocol_Reservation_descriptor,
        new String[] { "ClientName", "NoSeats", "Trip", });
    internal_static_transportAgency_protobufprotocol_Seat_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_transportAgency_protobufprotocol_Seat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_transportAgency_protobufprotocol_Seat_descriptor,
        new String[] { "SeatNo", "ClientName", });
    internal_static_transportAgency_protobufprotocol_Request_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_transportAgency_protobufprotocol_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_transportAgency_protobufprotocol_Request_descriptor,
        new String[] { "Type", "Trip", "Employee", "Reservation", "Payload", });
    internal_static_transportAgency_protobufprotocol_Response_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_transportAgency_protobufprotocol_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_transportAgency_protobufprotocol_Response_descriptor,
        new String[] { "Type", "Error", "Seats", "Trips", "Reservation", "Employee", "Trip", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
