// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ProtoDef.proto
// Protobuf Java Version: 4.30.2

package transportAgency.protobufprotocol;

public interface ReservationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transportAgency.protobufprotocol.Reservation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clientName = 1;</code>
   * @return The clientName.
   */
  String getClientName();
  /**
   * <code>string clientName = 1;</code>
   * @return The bytes for clientName.
   */
  com.google.protobuf.ByteString
      getClientNameBytes();

  /**
   * <code>int32 noSeats = 2;</code>
   * @return The noSeats.
   */
  int getNoSeats();

  /**
   * <code>.transportAgency.protobufprotocol.Trip trip = 3;</code>
   * @return Whether the trip field is set.
   */
  boolean hasTrip();
  /**
   * <code>.transportAgency.protobufprotocol.Trip trip = 3;</code>
   * @return The trip.
   */
  Trip getTrip();
  /**
   * <code>.transportAgency.protobufprotocol.Trip trip = 3;</code>
   */
  TripOrBuilder getTripOrBuilder();
}
