// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ProtoDef.proto
// Protobuf Java Version: 4.30.2

package transportAgency.protobufprotocol;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transportAgency.protobufprotocol.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.transportAgency.protobufprotocol.Response.Type type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.transportAgency.protobufprotocol.Response.Type type = 1;</code>
   * @return The type.
   */
  Response.Type getType();

  /**
   * <code>string error = 2;</code>
   * @return The error.
   */
  String getError();
  /**
   * <code>string error = 2;</code>
   * @return The bytes for error.
   */
  com.google.protobuf.ByteString
      getErrorBytes();

  /**
   * <code>repeated .transportAgency.protobufprotocol.Seat seats = 3;</code>
   */
  java.util.List<Seat>
      getSeatsList();
  /**
   * <code>repeated .transportAgency.protobufprotocol.Seat seats = 3;</code>
   */
  Seat getSeats(int index);
  /**
   * <code>repeated .transportAgency.protobufprotocol.Seat seats = 3;</code>
   */
  int getSeatsCount();
  /**
   * <code>repeated .transportAgency.protobufprotocol.Seat seats = 3;</code>
   */
  java.util.List<? extends SeatOrBuilder>
      getSeatsOrBuilderList();
  /**
   * <code>repeated .transportAgency.protobufprotocol.Seat seats = 3;</code>
   */
  SeatOrBuilder getSeatsOrBuilder(
      int index);

  /**
   * <code>repeated .transportAgency.protobufprotocol.Trip trips = 4;</code>
   */
  java.util.List<Trip>
      getTripsList();
  /**
   * <code>repeated .transportAgency.protobufprotocol.Trip trips = 4;</code>
   */
  Trip getTrips(int index);
  /**
   * <code>repeated .transportAgency.protobufprotocol.Trip trips = 4;</code>
   */
  int getTripsCount();
  /**
   * <code>repeated .transportAgency.protobufprotocol.Trip trips = 4;</code>
   */
  java.util.List<? extends TripOrBuilder>
      getTripsOrBuilderList();
  /**
   * <code>repeated .transportAgency.protobufprotocol.Trip trips = 4;</code>
   */
  TripOrBuilder getTripsOrBuilder(
      int index);

  /**
   * <code>.transportAgency.protobufprotocol.Reservation reservation = 5;</code>
   * @return Whether the reservation field is set.
   */
  boolean hasReservation();
  /**
   * <code>.transportAgency.protobufprotocol.Reservation reservation = 5;</code>
   * @return The reservation.
   */
  Reservation getReservation();
  /**
   * <code>.transportAgency.protobufprotocol.Reservation reservation = 5;</code>
   */
  ReservationOrBuilder getReservationOrBuilder();

  /**
   * <code>.transportAgency.protobufprotocol.Employee employee = 6;</code>
   * @return Whether the employee field is set.
   */
  boolean hasEmployee();
  /**
   * <code>.transportAgency.protobufprotocol.Employee employee = 6;</code>
   * @return The employee.
   */
  Employee getEmployee();
  /**
   * <code>.transportAgency.protobufprotocol.Employee employee = 6;</code>
   */
  EmployeeOrBuilder getEmployeeOrBuilder();

  /**
   * <code>.transportAgency.protobufprotocol.Trip trip = 7;</code>
   * @return Whether the trip field is set.
   */
  boolean hasTrip();
  /**
   * <code>.transportAgency.protobufprotocol.Trip trip = 7;</code>
   * @return The trip.
   */
  Trip getTrip();
  /**
   * <code>.transportAgency.protobufprotocol.Trip trip = 7;</code>
   */
  TripOrBuilder getTripOrBuilder();
}
