// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ProtoDef.proto
// Protobuf Java Version: 4.30.2

package transportAgency.protobufprotocol;

/**
 * Protobuf type {@code transportAgency.protobufprotocol.Response}
 */
public final class Response extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:transportAgency.protobufprotocol.Response)
    ResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      Response.class.getName());
  }
  // Use Response.newBuilder() to construct.
  private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Response() {
    type_ = 0;
    error_ = "";
    seats_ = java.util.Collections.emptyList();
    trips_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ProtoDefGenerated.internal_static_transportAgency_protobufprotocol_Response_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ProtoDefGenerated.internal_static_transportAgency_protobufprotocol_Response_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Response.class, Builder.class);
  }

  /**
   * Protobuf enum {@code transportAgency.protobufprotocol.Response.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Unknown = 0;</code>
     */
    Unknown(0),
    /**
     * <code>Ok = 1;</code>
     */
    Ok(1),
    /**
     * <code>Error = 2;</code>
     */
    Error(2),
    /**
     * <code>FindSeats = 3;</code>
     */
    FindSeats(3),
    /**
     * <code>FindTrips = 4;</code>
     */
    FindTrips(4),
    /**
     * <code>MakeReservation = 5;</code>
     */
    MakeReservation(5),
    /**
     * <code>FindEmployee = 6;</code>
     */
    FindEmployee(6),
    /**
     * <code>FindTrip = 7;</code>
     */
    FindTrip(7),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        Type.class.getName());
    }
    /**
     * <code>Unknown = 0;</code>
     */
    public static final int Unknown_VALUE = 0;
    /**
     * <code>Ok = 1;</code>
     */
    public static final int Ok_VALUE = 1;
    /**
     * <code>Error = 2;</code>
     */
    public static final int Error_VALUE = 2;
    /**
     * <code>FindSeats = 3;</code>
     */
    public static final int FindSeats_VALUE = 3;
    /**
     * <code>FindTrips = 4;</code>
     */
    public static final int FindTrips_VALUE = 4;
    /**
     * <code>MakeReservation = 5;</code>
     */
    public static final int MakeReservation_VALUE = 5;
    /**
     * <code>FindEmployee = 6;</code>
     */
    public static final int FindEmployee_VALUE = 6;
    /**
     * <code>FindTrip = 7;</code>
     */
    public static final int FindTrip_VALUE = 7;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Type forNumber(int value) {
      switch (value) {
        case 0: return Unknown;
        case 1: return Ok;
        case 2: return Error;
        case 3: return FindSeats;
        case 4: return FindTrips;
        case 5: return MakeReservation;
        case 6: return FindEmployee;
        case 7: return FindTrip;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Response.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:transportAgency.protobufprotocol.Response.Type)
  }

  private int bitField0_;
  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_ = 0;
  /**
   * <code>.transportAgency.protobufprotocol.Response.Type type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  @Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.transportAgency.protobufprotocol.Response.Type type = 1;</code>
   * @return The type.
   */
  @Override public Type getType() {
    Type result = Type.forNumber(type_);
    return result == null ? Type.UNRECOGNIZED : result;
  }

  public static final int ERROR_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object error_ = "";
  /**
   * <code>string error = 2;</code>
   * @return The error.
   */
  @Override
  public String getError() {
    Object ref = error_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      error_ = s;
      return s;
    }
  }
  /**
   * <code>string error = 2;</code>
   * @return The bytes for error.
   */
  @Override
  public com.google.protobuf.ByteString
      getErrorBytes() {
    Object ref = error_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      error_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEATS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<Seat> seats_;
  /**
   * <code>repeated .transportAgency.protobufprotocol.Seat seats = 3;</code>
   */
  @Override
  public java.util.List<Seat> getSeatsList() {
    return seats_;
  }
  /**
   * <code>repeated .transportAgency.protobufprotocol.Seat seats = 3;</code>
   */
  @Override
  public java.util.List<? extends SeatOrBuilder>
      getSeatsOrBuilderList() {
    return seats_;
  }
  /**
   * <code>repeated .transportAgency.protobufprotocol.Seat seats = 3;</code>
   */
  @Override
  public int getSeatsCount() {
    return seats_.size();
  }
  /**
   * <code>repeated .transportAgency.protobufprotocol.Seat seats = 3;</code>
   */
  @Override
  public Seat getSeats(int index) {
    return seats_.get(index);
  }
  /**
   * <code>repeated .transportAgency.protobufprotocol.Seat seats = 3;</code>
   */
  @Override
  public SeatOrBuilder getSeatsOrBuilder(
      int index) {
    return seats_.get(index);
  }

  public static final int TRIPS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<Trip> trips_;
  /**
   * <code>repeated .transportAgency.protobufprotocol.Trip trips = 4;</code>
   */
  @Override
  public java.util.List<Trip> getTripsList() {
    return trips_;
  }
  /**
   * <code>repeated .transportAgency.protobufprotocol.Trip trips = 4;</code>
   */
  @Override
  public java.util.List<? extends TripOrBuilder>
      getTripsOrBuilderList() {
    return trips_;
  }
  /**
   * <code>repeated .transportAgency.protobufprotocol.Trip trips = 4;</code>
   */
  @Override
  public int getTripsCount() {
    return trips_.size();
  }
  /**
   * <code>repeated .transportAgency.protobufprotocol.Trip trips = 4;</code>
   */
  @Override
  public Trip getTrips(int index) {
    return trips_.get(index);
  }
  /**
   * <code>repeated .transportAgency.protobufprotocol.Trip trips = 4;</code>
   */
  @Override
  public TripOrBuilder getTripsOrBuilder(
      int index) {
    return trips_.get(index);
  }

  public static final int RESERVATION_FIELD_NUMBER = 5;
  private Reservation reservation_;
  /**
   * <code>.transportAgency.protobufprotocol.Reservation reservation = 5;</code>
   * @return Whether the reservation field is set.
   */
  @Override
  public boolean hasReservation() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.transportAgency.protobufprotocol.Reservation reservation = 5;</code>
   * @return The reservation.
   */
  @Override
  public Reservation getReservation() {
    return reservation_ == null ? Reservation.getDefaultInstance() : reservation_;
  }
  /**
   * <code>.transportAgency.protobufprotocol.Reservation reservation = 5;</code>
   */
  @Override
  public ReservationOrBuilder getReservationOrBuilder() {
    return reservation_ == null ? Reservation.getDefaultInstance() : reservation_;
  }

  public static final int EMPLOYEE_FIELD_NUMBER = 6;
  private Employee employee_;
  /**
   * <code>.transportAgency.protobufprotocol.Employee employee = 6;</code>
   * @return Whether the employee field is set.
   */
  @Override
  public boolean hasEmployee() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.transportAgency.protobufprotocol.Employee employee = 6;</code>
   * @return The employee.
   */
  @Override
  public Employee getEmployee() {
    return employee_ == null ? Employee.getDefaultInstance() : employee_;
  }
  /**
   * <code>.transportAgency.protobufprotocol.Employee employee = 6;</code>
   */
  @Override
  public EmployeeOrBuilder getEmployeeOrBuilder() {
    return employee_ == null ? Employee.getDefaultInstance() : employee_;
  }

  public static final int TRIP_FIELD_NUMBER = 7;
  private Trip trip_;
  /**
   * <code>.transportAgency.protobufprotocol.Trip trip = 7;</code>
   * @return Whether the trip field is set.
   */
  @Override
  public boolean hasTrip() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.transportAgency.protobufprotocol.Trip trip = 7;</code>
   * @return The trip.
   */
  @Override
  public Trip getTrip() {
    return trip_ == null ? Trip.getDefaultInstance() : trip_;
  }
  /**
   * <code>.transportAgency.protobufprotocol.Trip trip = 7;</code>
   */
  @Override
  public TripOrBuilder getTripOrBuilder() {
    return trip_ == null ? Trip.getDefaultInstance() : trip_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != Type.Unknown.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(error_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, error_);
    }
    for (int i = 0; i < seats_.size(); i++) {
      output.writeMessage(3, seats_.get(i));
    }
    for (int i = 0; i < trips_.size(); i++) {
      output.writeMessage(4, trips_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(5, getReservation());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(6, getEmployee());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(7, getTrip());
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != Type.Unknown.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(error_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, error_);
    }
    for (int i = 0; i < seats_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, seats_.get(i));
    }
    for (int i = 0; i < trips_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, trips_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getReservation());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getEmployee());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getTrip());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Response)) {
      return super.equals(obj);
    }
    Response other = (Response) obj;

    if (type_ != other.type_) return false;
    if (!getError()
        .equals(other.getError())) return false;
    if (!getSeatsList()
        .equals(other.getSeatsList())) return false;
    if (!getTripsList()
        .equals(other.getTripsList())) return false;
    if (hasReservation() != other.hasReservation()) return false;
    if (hasReservation()) {
      if (!getReservation()
          .equals(other.getReservation())) return false;
    }
    if (hasEmployee() != other.hasEmployee()) return false;
    if (hasEmployee()) {
      if (!getEmployee()
          .equals(other.getEmployee())) return false;
    }
    if (hasTrip() != other.hasTrip()) return false;
    if (hasTrip()) {
      if (!getTrip()
          .equals(other.getTrip())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + ERROR_FIELD_NUMBER;
    hash = (53 * hash) + getError().hashCode();
    if (getSeatsCount() > 0) {
      hash = (37 * hash) + SEATS_FIELD_NUMBER;
      hash = (53 * hash) + getSeatsList().hashCode();
    }
    if (getTripsCount() > 0) {
      hash = (37 * hash) + TRIPS_FIELD_NUMBER;
      hash = (53 * hash) + getTripsList().hashCode();
    }
    if (hasReservation()) {
      hash = (37 * hash) + RESERVATION_FIELD_NUMBER;
      hash = (53 * hash) + getReservation().hashCode();
    }
    if (hasEmployee()) {
      hash = (37 * hash) + EMPLOYEE_FIELD_NUMBER;
      hash = (53 * hash) + getEmployee().hashCode();
    }
    if (hasTrip()) {
      hash = (37 * hash) + TRIP_FIELD_NUMBER;
      hash = (53 * hash) + getTrip().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Response parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Response parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Response parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Response parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Response parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Response parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Response parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static Response parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Response parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static Response parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Response parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static Response parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Response prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code transportAgency.protobufprotocol.Response}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:transportAgency.protobufprotocol.Response)
      ResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoDefGenerated.internal_static_transportAgency_protobufprotocol_Response_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoDefGenerated.internal_static_transportAgency_protobufprotocol_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Response.class, Builder.class);
    }

    // Construct using transportAgency.protobufprotocol.Response.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetSeatsFieldBuilder();
        internalGetTripsFieldBuilder();
        internalGetReservationFieldBuilder();
        internalGetEmployeeFieldBuilder();
        internalGetTripFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      type_ = 0;
      error_ = "";
      if (seatsBuilder_ == null) {
        seats_ = java.util.Collections.emptyList();
      } else {
        seats_ = null;
        seatsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      if (tripsBuilder_ == null) {
        trips_ = java.util.Collections.emptyList();
      } else {
        trips_ = null;
        tripsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      reservation_ = null;
      if (reservationBuilder_ != null) {
        reservationBuilder_.dispose();
        reservationBuilder_ = null;
      }
      employee_ = null;
      if (employeeBuilder_ != null) {
        employeeBuilder_.dispose();
        employeeBuilder_ = null;
      }
      trip_ = null;
      if (tripBuilder_ != null) {
        tripBuilder_.dispose();
        tripBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ProtoDefGenerated.internal_static_transportAgency_protobufprotocol_Response_descriptor;
    }

    @Override
    public Response getDefaultInstanceForType() {
      return Response.getDefaultInstance();
    }

    @Override
    public Response build() {
      Response result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Response buildPartial() {
      Response result = new Response(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(Response result) {
      if (seatsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          seats_ = java.util.Collections.unmodifiableList(seats_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.seats_ = seats_;
      } else {
        result.seats_ = seatsBuilder_.build();
      }
      if (tripsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          trips_ = java.util.Collections.unmodifiableList(trips_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.trips_ = trips_;
      } else {
        result.trips_ = tripsBuilder_.build();
      }
    }

    private void buildPartial0(Response result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.error_ = error_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.reservation_ = reservationBuilder_ == null
            ? reservation_
            : reservationBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.employee_ = employeeBuilder_ == null
            ? employee_
            : employeeBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.trip_ = tripBuilder_ == null
            ? trip_
            : tripBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Response) {
        return mergeFrom((Response)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Response other) {
      if (other == Response.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (!other.getError().isEmpty()) {
        error_ = other.error_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (seatsBuilder_ == null) {
        if (!other.seats_.isEmpty()) {
          if (seats_.isEmpty()) {
            seats_ = other.seats_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureSeatsIsMutable();
            seats_.addAll(other.seats_);
          }
          onChanged();
        }
      } else {
        if (!other.seats_.isEmpty()) {
          if (seatsBuilder_.isEmpty()) {
            seatsBuilder_.dispose();
            seatsBuilder_ = null;
            seats_ = other.seats_;
            bitField0_ = (bitField0_ & ~0x00000004);
            seatsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetSeatsFieldBuilder() : null;
          } else {
            seatsBuilder_.addAllMessages(other.seats_);
          }
        }
      }
      if (tripsBuilder_ == null) {
        if (!other.trips_.isEmpty()) {
          if (trips_.isEmpty()) {
            trips_ = other.trips_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureTripsIsMutable();
            trips_.addAll(other.trips_);
          }
          onChanged();
        }
      } else {
        if (!other.trips_.isEmpty()) {
          if (tripsBuilder_.isEmpty()) {
            tripsBuilder_.dispose();
            tripsBuilder_ = null;
            trips_ = other.trips_;
            bitField0_ = (bitField0_ & ~0x00000008);
            tripsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetTripsFieldBuilder() : null;
          } else {
            tripsBuilder_.addAllMessages(other.trips_);
          }
        }
      }
      if (other.hasReservation()) {
        mergeReservation(other.getReservation());
      }
      if (other.hasEmployee()) {
        mergeEmployee(other.getEmployee());
      }
      if (other.hasTrip()) {
        mergeTrip(other.getTrip());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              error_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              Seat m =
                  input.readMessage(
                      Seat.parser(),
                      extensionRegistry);
              if (seatsBuilder_ == null) {
                ensureSeatsIsMutable();
                seats_.add(m);
              } else {
                seatsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              Trip m =
                  input.readMessage(
                      Trip.parser(),
                      extensionRegistry);
              if (tripsBuilder_ == null) {
                ensureTripsIsMutable();
                trips_.add(m);
              } else {
                tripsBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  internalGetReservationFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  internalGetEmployeeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  internalGetTripFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int type_ = 0;
    /**
     * <code>.transportAgency.protobufprotocol.Response.Type type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Response.Type type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Response.Type type = 1;</code>
     * @return The type.
     */
    @Override
    public Type getType() {
      Type result = Type.forNumber(type_);
      return result == null ? Type.UNRECOGNIZED : result;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Response.Type type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(Type value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Response.Type type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;
      onChanged();
      return this;
    }

    private Object error_ = "";
    /**
     * <code>string error = 2;</code>
     * @return The error.
     */
    public String getError() {
      Object ref = error_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        error_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string error = 2;</code>
     * @return The bytes for error.
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      Object ref = error_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string error = 2;</code>
     * @param value The error to set.
     * @return This builder for chaining.
     */
    public Builder setError(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      error_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string error = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearError() {
      error_ = getDefaultInstance().getError();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string error = 2;</code>
     * @param value The bytes for error to set.
     * @return This builder for chaining.
     */
    public Builder setErrorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      error_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.util.List<Seat> seats_ =
      java.util.Collections.emptyList();
    private void ensureSeatsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        seats_ = new java.util.ArrayList<Seat>(seats_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        Seat, Seat.Builder, SeatOrBuilder> seatsBuilder_;

    /**
     * <code>repeated .transportAgency.protobufprotocol.Seat seats = 3;</code>
     */
    public java.util.List<Seat> getSeatsList() {
      if (seatsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(seats_);
      } else {
        return seatsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Seat seats = 3;</code>
     */
    public int getSeatsCount() {
      if (seatsBuilder_ == null) {
        return seats_.size();
      } else {
        return seatsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Seat seats = 3;</code>
     */
    public Seat getSeats(int index) {
      if (seatsBuilder_ == null) {
        return seats_.get(index);
      } else {
        return seatsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Seat seats = 3;</code>
     */
    public Builder setSeats(
        int index, Seat value) {
      if (seatsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSeatsIsMutable();
        seats_.set(index, value);
        onChanged();
      } else {
        seatsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Seat seats = 3;</code>
     */
    public Builder setSeats(
        int index, Seat.Builder builderForValue) {
      if (seatsBuilder_ == null) {
        ensureSeatsIsMutable();
        seats_.set(index, builderForValue.build());
        onChanged();
      } else {
        seatsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Seat seats = 3;</code>
     */
    public Builder addSeats(Seat value) {
      if (seatsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSeatsIsMutable();
        seats_.add(value);
        onChanged();
      } else {
        seatsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Seat seats = 3;</code>
     */
    public Builder addSeats(
        int index, Seat value) {
      if (seatsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSeatsIsMutable();
        seats_.add(index, value);
        onChanged();
      } else {
        seatsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Seat seats = 3;</code>
     */
    public Builder addSeats(
        Seat.Builder builderForValue) {
      if (seatsBuilder_ == null) {
        ensureSeatsIsMutable();
        seats_.add(builderForValue.build());
        onChanged();
      } else {
        seatsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Seat seats = 3;</code>
     */
    public Builder addSeats(
        int index, Seat.Builder builderForValue) {
      if (seatsBuilder_ == null) {
        ensureSeatsIsMutable();
        seats_.add(index, builderForValue.build());
        onChanged();
      } else {
        seatsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Seat seats = 3;</code>
     */
    public Builder addAllSeats(
        Iterable<? extends Seat> values) {
      if (seatsBuilder_ == null) {
        ensureSeatsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, seats_);
        onChanged();
      } else {
        seatsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Seat seats = 3;</code>
     */
    public Builder clearSeats() {
      if (seatsBuilder_ == null) {
        seats_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        seatsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Seat seats = 3;</code>
     */
    public Builder removeSeats(int index) {
      if (seatsBuilder_ == null) {
        ensureSeatsIsMutable();
        seats_.remove(index);
        onChanged();
      } else {
        seatsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Seat seats = 3;</code>
     */
    public Seat.Builder getSeatsBuilder(
        int index) {
      return internalGetSeatsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Seat seats = 3;</code>
     */
    public SeatOrBuilder getSeatsOrBuilder(
        int index) {
      if (seatsBuilder_ == null) {
        return seats_.get(index);  } else {
        return seatsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Seat seats = 3;</code>
     */
    public java.util.List<? extends SeatOrBuilder>
         getSeatsOrBuilderList() {
      if (seatsBuilder_ != null) {
        return seatsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(seats_);
      }
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Seat seats = 3;</code>
     */
    public Seat.Builder addSeatsBuilder() {
      return internalGetSeatsFieldBuilder().addBuilder(
          Seat.getDefaultInstance());
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Seat seats = 3;</code>
     */
    public Seat.Builder addSeatsBuilder(
        int index) {
      return internalGetSeatsFieldBuilder().addBuilder(
          index, Seat.getDefaultInstance());
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Seat seats = 3;</code>
     */
    public java.util.List<Seat.Builder>
         getSeatsBuilderList() {
      return internalGetSeatsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        Seat, Seat.Builder, SeatOrBuilder>
        internalGetSeatsFieldBuilder() {
      if (seatsBuilder_ == null) {
        seatsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            Seat, Seat.Builder, SeatOrBuilder>(
                seats_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        seats_ = null;
      }
      return seatsBuilder_;
    }

    private java.util.List<Trip> trips_ =
      java.util.Collections.emptyList();
    private void ensureTripsIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        trips_ = new java.util.ArrayList<Trip>(trips_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        Trip, Trip.Builder, TripOrBuilder> tripsBuilder_;

    /**
     * <code>repeated .transportAgency.protobufprotocol.Trip trips = 4;</code>
     */
    public java.util.List<Trip> getTripsList() {
      if (tripsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(trips_);
      } else {
        return tripsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Trip trips = 4;</code>
     */
    public int getTripsCount() {
      if (tripsBuilder_ == null) {
        return trips_.size();
      } else {
        return tripsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Trip trips = 4;</code>
     */
    public Trip getTrips(int index) {
      if (tripsBuilder_ == null) {
        return trips_.get(index);
      } else {
        return tripsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Trip trips = 4;</code>
     */
    public Builder setTrips(
        int index, Trip value) {
      if (tripsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTripsIsMutable();
        trips_.set(index, value);
        onChanged();
      } else {
        tripsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Trip trips = 4;</code>
     */
    public Builder setTrips(
        int index, Trip.Builder builderForValue) {
      if (tripsBuilder_ == null) {
        ensureTripsIsMutable();
        trips_.set(index, builderForValue.build());
        onChanged();
      } else {
        tripsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Trip trips = 4;</code>
     */
    public Builder addTrips(Trip value) {
      if (tripsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTripsIsMutable();
        trips_.add(value);
        onChanged();
      } else {
        tripsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Trip trips = 4;</code>
     */
    public Builder addTrips(
        int index, Trip value) {
      if (tripsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTripsIsMutable();
        trips_.add(index, value);
        onChanged();
      } else {
        tripsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Trip trips = 4;</code>
     */
    public Builder addTrips(
        Trip.Builder builderForValue) {
      if (tripsBuilder_ == null) {
        ensureTripsIsMutable();
        trips_.add(builderForValue.build());
        onChanged();
      } else {
        tripsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Trip trips = 4;</code>
     */
    public Builder addTrips(
        int index, Trip.Builder builderForValue) {
      if (tripsBuilder_ == null) {
        ensureTripsIsMutable();
        trips_.add(index, builderForValue.build());
        onChanged();
      } else {
        tripsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Trip trips = 4;</code>
     */
    public Builder addAllTrips(
        Iterable<? extends Trip> values) {
      if (tripsBuilder_ == null) {
        ensureTripsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, trips_);
        onChanged();
      } else {
        tripsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Trip trips = 4;</code>
     */
    public Builder clearTrips() {
      if (tripsBuilder_ == null) {
        trips_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        tripsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Trip trips = 4;</code>
     */
    public Builder removeTrips(int index) {
      if (tripsBuilder_ == null) {
        ensureTripsIsMutable();
        trips_.remove(index);
        onChanged();
      } else {
        tripsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Trip trips = 4;</code>
     */
    public Trip.Builder getTripsBuilder(
        int index) {
      return internalGetTripsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Trip trips = 4;</code>
     */
    public TripOrBuilder getTripsOrBuilder(
        int index) {
      if (tripsBuilder_ == null) {
        return trips_.get(index);  } else {
        return tripsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Trip trips = 4;</code>
     */
    public java.util.List<? extends TripOrBuilder>
         getTripsOrBuilderList() {
      if (tripsBuilder_ != null) {
        return tripsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(trips_);
      }
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Trip trips = 4;</code>
     */
    public Trip.Builder addTripsBuilder() {
      return internalGetTripsFieldBuilder().addBuilder(
          Trip.getDefaultInstance());
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Trip trips = 4;</code>
     */
    public Trip.Builder addTripsBuilder(
        int index) {
      return internalGetTripsFieldBuilder().addBuilder(
          index, Trip.getDefaultInstance());
    }
    /**
     * <code>repeated .transportAgency.protobufprotocol.Trip trips = 4;</code>
     */
    public java.util.List<Trip.Builder>
         getTripsBuilderList() {
      return internalGetTripsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        Trip, Trip.Builder, TripOrBuilder>
        internalGetTripsFieldBuilder() {
      if (tripsBuilder_ == null) {
        tripsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            Trip, Trip.Builder, TripOrBuilder>(
                trips_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        trips_ = null;
      }
      return tripsBuilder_;
    }

    private Reservation reservation_;
    private com.google.protobuf.SingleFieldBuilder<
        Reservation, Reservation.Builder, ReservationOrBuilder> reservationBuilder_;
    /**
     * <code>.transportAgency.protobufprotocol.Reservation reservation = 5;</code>
     * @return Whether the reservation field is set.
     */
    public boolean hasReservation() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.transportAgency.protobufprotocol.Reservation reservation = 5;</code>
     * @return The reservation.
     */
    public Reservation getReservation() {
      if (reservationBuilder_ == null) {
        return reservation_ == null ? Reservation.getDefaultInstance() : reservation_;
      } else {
        return reservationBuilder_.getMessage();
      }
    }
    /**
     * <code>.transportAgency.protobufprotocol.Reservation reservation = 5;</code>
     */
    public Builder setReservation(Reservation value) {
      if (reservationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        reservation_ = value;
      } else {
        reservationBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Reservation reservation = 5;</code>
     */
    public Builder setReservation(
        Reservation.Builder builderForValue) {
      if (reservationBuilder_ == null) {
        reservation_ = builderForValue.build();
      } else {
        reservationBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Reservation reservation = 5;</code>
     */
    public Builder mergeReservation(Reservation value) {
      if (reservationBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          reservation_ != null &&
          reservation_ != Reservation.getDefaultInstance()) {
          getReservationBuilder().mergeFrom(value);
        } else {
          reservation_ = value;
        }
      } else {
        reservationBuilder_.mergeFrom(value);
      }
      if (reservation_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Reservation reservation = 5;</code>
     */
    public Builder clearReservation() {
      bitField0_ = (bitField0_ & ~0x00000010);
      reservation_ = null;
      if (reservationBuilder_ != null) {
        reservationBuilder_.dispose();
        reservationBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Reservation reservation = 5;</code>
     */
    public Reservation.Builder getReservationBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return internalGetReservationFieldBuilder().getBuilder();
    }
    /**
     * <code>.transportAgency.protobufprotocol.Reservation reservation = 5;</code>
     */
    public ReservationOrBuilder getReservationOrBuilder() {
      if (reservationBuilder_ != null) {
        return reservationBuilder_.getMessageOrBuilder();
      } else {
        return reservation_ == null ?
            Reservation.getDefaultInstance() : reservation_;
      }
    }
    /**
     * <code>.transportAgency.protobufprotocol.Reservation reservation = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        Reservation, Reservation.Builder, ReservationOrBuilder>
        internalGetReservationFieldBuilder() {
      if (reservationBuilder_ == null) {
        reservationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            Reservation, Reservation.Builder, ReservationOrBuilder>(
                getReservation(),
                getParentForChildren(),
                isClean());
        reservation_ = null;
      }
      return reservationBuilder_;
    }

    private Employee employee_;
    private com.google.protobuf.SingleFieldBuilder<
        Employee, Employee.Builder, EmployeeOrBuilder> employeeBuilder_;
    /**
     * <code>.transportAgency.protobufprotocol.Employee employee = 6;</code>
     * @return Whether the employee field is set.
     */
    public boolean hasEmployee() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.transportAgency.protobufprotocol.Employee employee = 6;</code>
     * @return The employee.
     */
    public Employee getEmployee() {
      if (employeeBuilder_ == null) {
        return employee_ == null ? Employee.getDefaultInstance() : employee_;
      } else {
        return employeeBuilder_.getMessage();
      }
    }
    /**
     * <code>.transportAgency.protobufprotocol.Employee employee = 6;</code>
     */
    public Builder setEmployee(Employee value) {
      if (employeeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        employee_ = value;
      } else {
        employeeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Employee employee = 6;</code>
     */
    public Builder setEmployee(
        Employee.Builder builderForValue) {
      if (employeeBuilder_ == null) {
        employee_ = builderForValue.build();
      } else {
        employeeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Employee employee = 6;</code>
     */
    public Builder mergeEmployee(Employee value) {
      if (employeeBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          employee_ != null &&
          employee_ != Employee.getDefaultInstance()) {
          getEmployeeBuilder().mergeFrom(value);
        } else {
          employee_ = value;
        }
      } else {
        employeeBuilder_.mergeFrom(value);
      }
      if (employee_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Employee employee = 6;</code>
     */
    public Builder clearEmployee() {
      bitField0_ = (bitField0_ & ~0x00000020);
      employee_ = null;
      if (employeeBuilder_ != null) {
        employeeBuilder_.dispose();
        employeeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Employee employee = 6;</code>
     */
    public Employee.Builder getEmployeeBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return internalGetEmployeeFieldBuilder().getBuilder();
    }
    /**
     * <code>.transportAgency.protobufprotocol.Employee employee = 6;</code>
     */
    public EmployeeOrBuilder getEmployeeOrBuilder() {
      if (employeeBuilder_ != null) {
        return employeeBuilder_.getMessageOrBuilder();
      } else {
        return employee_ == null ?
            Employee.getDefaultInstance() : employee_;
      }
    }
    /**
     * <code>.transportAgency.protobufprotocol.Employee employee = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        Employee, Employee.Builder, EmployeeOrBuilder>
        internalGetEmployeeFieldBuilder() {
      if (employeeBuilder_ == null) {
        employeeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            Employee, Employee.Builder, EmployeeOrBuilder>(
                getEmployee(),
                getParentForChildren(),
                isClean());
        employee_ = null;
      }
      return employeeBuilder_;
    }

    private Trip trip_;
    private com.google.protobuf.SingleFieldBuilder<
        Trip, Trip.Builder, TripOrBuilder> tripBuilder_;
    /**
     * <code>.transportAgency.protobufprotocol.Trip trip = 7;</code>
     * @return Whether the trip field is set.
     */
    public boolean hasTrip() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>.transportAgency.protobufprotocol.Trip trip = 7;</code>
     * @return The trip.
     */
    public Trip getTrip() {
      if (tripBuilder_ == null) {
        return trip_ == null ? Trip.getDefaultInstance() : trip_;
      } else {
        return tripBuilder_.getMessage();
      }
    }
    /**
     * <code>.transportAgency.protobufprotocol.Trip trip = 7;</code>
     */
    public Builder setTrip(Trip value) {
      if (tripBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        trip_ = value;
      } else {
        tripBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Trip trip = 7;</code>
     */
    public Builder setTrip(
        Trip.Builder builderForValue) {
      if (tripBuilder_ == null) {
        trip_ = builderForValue.build();
      } else {
        tripBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Trip trip = 7;</code>
     */
    public Builder mergeTrip(Trip value) {
      if (tripBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          trip_ != null &&
          trip_ != Trip.getDefaultInstance()) {
          getTripBuilder().mergeFrom(value);
        } else {
          trip_ = value;
        }
      } else {
        tripBuilder_.mergeFrom(value);
      }
      if (trip_ != null) {
        bitField0_ |= 0x00000040;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Trip trip = 7;</code>
     */
    public Builder clearTrip() {
      bitField0_ = (bitField0_ & ~0x00000040);
      trip_ = null;
      if (tripBuilder_ != null) {
        tripBuilder_.dispose();
        tripBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Trip trip = 7;</code>
     */
    public Trip.Builder getTripBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return internalGetTripFieldBuilder().getBuilder();
    }
    /**
     * <code>.transportAgency.protobufprotocol.Trip trip = 7;</code>
     */
    public TripOrBuilder getTripOrBuilder() {
      if (tripBuilder_ != null) {
        return tripBuilder_.getMessageOrBuilder();
      } else {
        return trip_ == null ?
            Trip.getDefaultInstance() : trip_;
      }
    }
    /**
     * <code>.transportAgency.protobufprotocol.Trip trip = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        Trip, Trip.Builder, TripOrBuilder>
        internalGetTripFieldBuilder() {
      if (tripBuilder_ == null) {
        tripBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            Trip, Trip.Builder, TripOrBuilder>(
                getTrip(),
                getParentForChildren(),
                isClean());
        trip_ = null;
      }
      return tripBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:transportAgency.protobufprotocol.Response)
  }

  // @@protoc_insertion_point(class_scope:transportAgency.protobufprotocol.Response)
  private static final Response DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Response();
  }

  public static Response getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Response>
      PARSER = new com.google.protobuf.AbstractParser<Response>() {
    @Override
    public Response parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Response> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Response> getParserForType() {
    return PARSER;
  }

  @Override
  public Response getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

