// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ProtoDef.proto
// Protobuf Java Version: 4.30.2

package transportAgency.protobufprotocol;

public interface SeatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transportAgency.protobufprotocol.Seat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 seatNo = 1;</code>
   * @return The seatNo.
   */
  int getSeatNo();

  /**
   * <code>string clientName = 2;</code>
   * @return The clientName.
   */
  String getClientName();
  /**
   * <code>string clientName = 2;</code>
   * @return The bytes for clientName.
   */
  com.google.protobuf.ByteString
      getClientNameBytes();
}
