// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ProtoDef.proto
// Protobuf Java Version: 4.30.2

package transportAgency.protobufprotocol;

/**
 * Protobuf type {@code transportAgency.protobufprotocol.Seat}
 */
public final class Seat extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:transportAgency.protobufprotocol.Seat)
    SeatOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      Seat.class.getName());
  }
  // Use Seat.newBuilder() to construct.
  private Seat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Seat() {
    clientName_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ProtoDefGenerated.internal_static_transportAgency_protobufprotocol_Seat_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ProtoDefGenerated.internal_static_transportAgency_protobufprotocol_Seat_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Seat.class, Builder.class);
  }

  public static final int SEATNO_FIELD_NUMBER = 1;
  private int seatNo_ = 0;
  /**
   * <code>int32 seatNo = 1;</code>
   * @return The seatNo.
   */
  @Override
  public int getSeatNo() {
    return seatNo_;
  }

  public static final int CLIENTNAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object clientName_ = "";
  /**
   * <code>string clientName = 2;</code>
   * @return The clientName.
   */
  @Override
  public String getClientName() {
    Object ref = clientName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      clientName_ = s;
      return s;
    }
  }
  /**
   * <code>string clientName = 2;</code>
   * @return The bytes for clientName.
   */
  @Override
  public com.google.protobuf.ByteString
      getClientNameBytes() {
    Object ref = clientName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      clientName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (seatNo_ != 0) {
      output.writeInt32(1, seatNo_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(clientName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, clientName_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (seatNo_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, seatNo_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(clientName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, clientName_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Seat)) {
      return super.equals(obj);
    }
    Seat other = (Seat) obj;

    if (getSeatNo()
        != other.getSeatNo()) return false;
    if (!getClientName()
        .equals(other.getClientName())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SEATNO_FIELD_NUMBER;
    hash = (53 * hash) + getSeatNo();
    hash = (37 * hash) + CLIENTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getClientName().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Seat parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Seat parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Seat parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Seat parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Seat parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Seat parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Seat parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static Seat parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Seat parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static Seat parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Seat parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static Seat parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Seat prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code transportAgency.protobufprotocol.Seat}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:transportAgency.protobufprotocol.Seat)
      SeatOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoDefGenerated.internal_static_transportAgency_protobufprotocol_Seat_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoDefGenerated.internal_static_transportAgency_protobufprotocol_Seat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Seat.class, Builder.class);
    }

    // Construct using transportAgency.protobufprotocol.Seat.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      seatNo_ = 0;
      clientName_ = "";
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ProtoDefGenerated.internal_static_transportAgency_protobufprotocol_Seat_descriptor;
    }

    @Override
    public Seat getDefaultInstanceForType() {
      return Seat.getDefaultInstance();
    }

    @Override
    public Seat build() {
      Seat result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Seat buildPartial() {
      Seat result = new Seat(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(Seat result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.seatNo_ = seatNo_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.clientName_ = clientName_;
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Seat) {
        return mergeFrom((Seat)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Seat other) {
      if (other == Seat.getDefaultInstance()) return this;
      if (other.getSeatNo() != 0) {
        setSeatNo(other.getSeatNo());
      }
      if (!other.getClientName().isEmpty()) {
        clientName_ = other.clientName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              seatNo_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              clientName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int seatNo_ ;
    /**
     * <code>int32 seatNo = 1;</code>
     * @return The seatNo.
     */
    @Override
    public int getSeatNo() {
      return seatNo_;
    }
    /**
     * <code>int32 seatNo = 1;</code>
     * @param value The seatNo to set.
     * @return This builder for chaining.
     */
    public Builder setSeatNo(int value) {

      seatNo_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 seatNo = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeatNo() {
      bitField0_ = (bitField0_ & ~0x00000001);
      seatNo_ = 0;
      onChanged();
      return this;
    }

    private Object clientName_ = "";
    /**
     * <code>string clientName = 2;</code>
     * @return The clientName.
     */
    public String getClientName() {
      Object ref = clientName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        clientName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string clientName = 2;</code>
     * @return The bytes for clientName.
     */
    public com.google.protobuf.ByteString
        getClientNameBytes() {
      Object ref = clientName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        clientName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string clientName = 2;</code>
     * @param value The clientName to set.
     * @return This builder for chaining.
     */
    public Builder setClientName(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      clientName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string clientName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientName() {
      clientName_ = getDefaultInstance().getClientName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string clientName = 2;</code>
     * @param value The bytes for clientName to set.
     * @return This builder for chaining.
     */
    public Builder setClientNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      clientName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:transportAgency.protobufprotocol.Seat)
  }

  // @@protoc_insertion_point(class_scope:transportAgency.protobufprotocol.Seat)
  private static final Seat DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Seat();
  }

  public static Seat getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Seat>
      PARSER = new com.google.protobuf.AbstractParser<Seat>() {
    @Override
    public Seat parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Seat> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Seat> getParserForType() {
    return PARSER;
  }

  @Override
  public Seat getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

