// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ProtoDef.proto
// Protobuf Java Version: 4.30.2

package transportAgency.protobufprotocol;

/**
 * Protobuf type {@code transportAgency.protobufprotocol.Trip}
 */
public final class Trip extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:transportAgency.protobufprotocol.Trip)
    TripOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      Trip.class.getName());
  }
  // Use Trip.newBuilder() to construct.
  private Trip(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Trip() {
    destination_ = "";
    departureDate_ = "";
    departureTime_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ProtoDefGenerated.internal_static_transportAgency_protobufprotocol_Trip_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ProtoDefGenerated.internal_static_transportAgency_protobufprotocol_Trip_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Trip.class, Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_ = 0L;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @Override
  public long getId() {
    return id_;
  }

  public static final int DESTINATION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object destination_ = "";
  /**
   * <code>string destination = 2;</code>
   * @return The destination.
   */
  @Override
  public String getDestination() {
    Object ref = destination_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      destination_ = s;
      return s;
    }
  }
  /**
   * <code>string destination = 2;</code>
   * @return The bytes for destination.
   */
  @Override
  public com.google.protobuf.ByteString
      getDestinationBytes() {
    Object ref = destination_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      destination_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEPARTUREDATE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile Object departureDate_ = "";
  /**
   * <code>string departureDate = 3;</code>
   * @return The departureDate.
   */
  @Override
  public String getDepartureDate() {
    Object ref = departureDate_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      departureDate_ = s;
      return s;
    }
  }
  /**
   * <code>string departureDate = 3;</code>
   * @return The bytes for departureDate.
   */
  @Override
  public com.google.protobuf.ByteString
      getDepartureDateBytes() {
    Object ref = departureDate_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      departureDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEPARTURETIME_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile Object departureTime_ = "";
  /**
   * <code>string departureTime = 4;</code>
   * @return The departureTime.
   */
  @Override
  public String getDepartureTime() {
    Object ref = departureTime_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      departureTime_ = s;
      return s;
    }
  }
  /**
   * <code>string departureTime = 4;</code>
   * @return The bytes for departureTime.
   */
  @Override
  public com.google.protobuf.ByteString
      getDepartureTimeBytes() {
    Object ref = departureTime_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      departureTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOSEATSAVAILABLE_FIELD_NUMBER = 5;
  private int noSeatsAvailable_ = 0;
  /**
   * <code>int32 noSeatsAvailable = 5;</code>
   * @return The noSeatsAvailable.
   */
  @Override
  public int getNoSeatsAvailable() {
    return noSeatsAvailable_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(destination_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, destination_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(departureDate_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, departureDate_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(departureTime_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, departureTime_);
    }
    if (noSeatsAvailable_ != 0) {
      output.writeInt32(5, noSeatsAvailable_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(destination_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, destination_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(departureDate_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, departureDate_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(departureTime_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, departureTime_);
    }
    if (noSeatsAvailable_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, noSeatsAvailable_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Trip)) {
      return super.equals(obj);
    }
    Trip other = (Trip) obj;

    if (getId()
        != other.getId()) return false;
    if (!getDestination()
        .equals(other.getDestination())) return false;
    if (!getDepartureDate()
        .equals(other.getDepartureDate())) return false;
    if (!getDepartureTime()
        .equals(other.getDepartureTime())) return false;
    if (getNoSeatsAvailable()
        != other.getNoSeatsAvailable()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + DESTINATION_FIELD_NUMBER;
    hash = (53 * hash) + getDestination().hashCode();
    hash = (37 * hash) + DEPARTUREDATE_FIELD_NUMBER;
    hash = (53 * hash) + getDepartureDate().hashCode();
    hash = (37 * hash) + DEPARTURETIME_FIELD_NUMBER;
    hash = (53 * hash) + getDepartureTime().hashCode();
    hash = (37 * hash) + NOSEATSAVAILABLE_FIELD_NUMBER;
    hash = (53 * hash) + getNoSeatsAvailable();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Trip parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Trip parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Trip parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Trip parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Trip parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Trip parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Trip parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static Trip parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Trip parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static Trip parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Trip parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static Trip parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Trip prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code transportAgency.protobufprotocol.Trip}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:transportAgency.protobufprotocol.Trip)
      TripOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoDefGenerated.internal_static_transportAgency_protobufprotocol_Trip_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoDefGenerated.internal_static_transportAgency_protobufprotocol_Trip_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Trip.class, Builder.class);
    }

    // Construct using transportAgency.protobufprotocol.Trip.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0L;
      destination_ = "";
      departureDate_ = "";
      departureTime_ = "";
      noSeatsAvailable_ = 0;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ProtoDefGenerated.internal_static_transportAgency_protobufprotocol_Trip_descriptor;
    }

    @Override
    public Trip getDefaultInstanceForType() {
      return Trip.getDefaultInstance();
    }

    @Override
    public Trip build() {
      Trip result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Trip buildPartial() {
      Trip result = new Trip(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(Trip result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.destination_ = destination_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.departureDate_ = departureDate_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.departureTime_ = departureTime_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.noSeatsAvailable_ = noSeatsAvailable_;
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Trip) {
        return mergeFrom((Trip)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Trip other) {
      if (other == Trip.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getDestination().isEmpty()) {
        destination_ = other.destination_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getDepartureDate().isEmpty()) {
        departureDate_ = other.departureDate_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getDepartureTime().isEmpty()) {
        departureTime_ = other.departureTime_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getNoSeatsAvailable() != 0) {
        setNoSeatsAvailable(other.getNoSeatsAvailable());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              destination_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              departureDate_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              departureTime_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              noSeatsAvailable_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private Object destination_ = "";
    /**
     * <code>string destination = 2;</code>
     * @return The destination.
     */
    public String getDestination() {
      Object ref = destination_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        destination_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string destination = 2;</code>
     * @return The bytes for destination.
     */
    public com.google.protobuf.ByteString
        getDestinationBytes() {
      Object ref = destination_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        destination_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string destination = 2;</code>
     * @param value The destination to set.
     * @return This builder for chaining.
     */
    public Builder setDestination(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      destination_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string destination = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDestination() {
      destination_ = getDefaultInstance().getDestination();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string destination = 2;</code>
     * @param value The bytes for destination to set.
     * @return This builder for chaining.
     */
    public Builder setDestinationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      destination_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private Object departureDate_ = "";
    /**
     * <code>string departureDate = 3;</code>
     * @return The departureDate.
     */
    public String getDepartureDate() {
      Object ref = departureDate_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        departureDate_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string departureDate = 3;</code>
     * @return The bytes for departureDate.
     */
    public com.google.protobuf.ByteString
        getDepartureDateBytes() {
      Object ref = departureDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        departureDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string departureDate = 3;</code>
     * @param value The departureDate to set.
     * @return This builder for chaining.
     */
    public Builder setDepartureDate(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      departureDate_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string departureDate = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDepartureDate() {
      departureDate_ = getDefaultInstance().getDepartureDate();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string departureDate = 3;</code>
     * @param value The bytes for departureDate to set.
     * @return This builder for chaining.
     */
    public Builder setDepartureDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      departureDate_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private Object departureTime_ = "";
    /**
     * <code>string departureTime = 4;</code>
     * @return The departureTime.
     */
    public String getDepartureTime() {
      Object ref = departureTime_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        departureTime_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string departureTime = 4;</code>
     * @return The bytes for departureTime.
     */
    public com.google.protobuf.ByteString
        getDepartureTimeBytes() {
      Object ref = departureTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        departureTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string departureTime = 4;</code>
     * @param value The departureTime to set.
     * @return This builder for chaining.
     */
    public Builder setDepartureTime(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      departureTime_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string departureTime = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDepartureTime() {
      departureTime_ = getDefaultInstance().getDepartureTime();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string departureTime = 4;</code>
     * @param value The bytes for departureTime to set.
     * @return This builder for chaining.
     */
    public Builder setDepartureTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      departureTime_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private int noSeatsAvailable_ ;
    /**
     * <code>int32 noSeatsAvailable = 5;</code>
     * @return The noSeatsAvailable.
     */
    @Override
    public int getNoSeatsAvailable() {
      return noSeatsAvailable_;
    }
    /**
     * <code>int32 noSeatsAvailable = 5;</code>
     * @param value The noSeatsAvailable to set.
     * @return This builder for chaining.
     */
    public Builder setNoSeatsAvailable(int value) {

      noSeatsAvailable_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 noSeatsAvailable = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearNoSeatsAvailable() {
      bitField0_ = (bitField0_ & ~0x00000010);
      noSeatsAvailable_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:transportAgency.protobufprotocol.Trip)
  }

  // @@protoc_insertion_point(class_scope:transportAgency.protobufprotocol.Trip)
  private static final Trip DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Trip();
  }

  public static Trip getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Trip>
      PARSER = new com.google.protobuf.AbstractParser<Trip>() {
    @Override
    public Trip parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Trip> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Trip> getParserForType() {
    return PARSER;
  }

  @Override
  public Trip getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

