// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ProtoDef.proto
// Protobuf Java Version: 4.30.2

package transportAgency.protobufprotocol;

public interface TripOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transportAgency.protobufprotocol.Trip)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string destination = 2;</code>
   * @return The destination.
   */
  String getDestination();
  /**
   * <code>string destination = 2;</code>
   * @return The bytes for destination.
   */
  com.google.protobuf.ByteString
      getDestinationBytes();

  /**
   * <code>string departureDate = 3;</code>
   * @return The departureDate.
   */
  String getDepartureDate();
  /**
   * <code>string departureDate = 3;</code>
   * @return The bytes for departureDate.
   */
  com.google.protobuf.ByteString
      getDepartureDateBytes();

  /**
   * <code>string departureTime = 4;</code>
   * @return The departureTime.
   */
  String getDepartureTime();
  /**
   * <code>string departureTime = 4;</code>
   * @return The bytes for departureTime.
   */
  com.google.protobuf.ByteString
      getDepartureTimeBytes();

  /**
   * <code>int32 noSeatsAvailable = 5;</code>
   * @return The noSeatsAvailable.
   */
  int getNoSeatsAvailable();
}
