// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ProtoDef.proto
// Protobuf Java Version: 4.30.2

package transportAgency.protobufprotocol;

/**
 * Protobuf type {@code transportAgency.protobufprotocol.Request}
 */
public final class Request extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:transportAgency.protobufprotocol.Request)
    RequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      Request.class.getName());
  }
  // Use Request.newBuilder() to construct.
  private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Request() {
    type_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return transportAgency.protobufprotocol.ProtoDefGenerated.internal_static_transportAgency_protobufprotocol_Request_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return transportAgency.protobufprotocol.ProtoDefGenerated.internal_static_transportAgency_protobufprotocol_Request_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            transportAgency.protobufprotocol.Request.class, transportAgency.protobufprotocol.Request.Builder.class);
  }

  /**
   * Protobuf enum {@code transportAgency.protobufprotocol.Request.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Unknown = 0;</code>
     */
    Unknown(0),
    /**
     * <code>Login = 1;</code>
     */
    Login(1),
    /**
     * <code>Logout = 2;</code>
     */
    Logout(2),
    /**
     * <code>FindSeats = 3;</code>
     */
    FindSeats(3),
    /**
     * <code>FindTrips = 4;</code>
     */
    FindTrips(4),
    /**
     * <code>MakeReservation = 5;</code>
     */
    MakeReservation(5),
    /**
     * <code>FindEmployee = 6;</code>
     */
    FindEmployee(6),
    /**
     * <code>FindTrip = 7;</code>
     */
    FindTrip(7),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        Type.class.getName());
    }
    /**
     * <code>Unknown = 0;</code>
     */
    public static final int Unknown_VALUE = 0;
    /**
     * <code>Login = 1;</code>
     */
    public static final int Login_VALUE = 1;
    /**
     * <code>Logout = 2;</code>
     */
    public static final int Logout_VALUE = 2;
    /**
     * <code>FindSeats = 3;</code>
     */
    public static final int FindSeats_VALUE = 3;
    /**
     * <code>FindTrips = 4;</code>
     */
    public static final int FindTrips_VALUE = 4;
    /**
     * <code>MakeReservation = 5;</code>
     */
    public static final int MakeReservation_VALUE = 5;
    /**
     * <code>FindEmployee = 6;</code>
     */
    public static final int FindEmployee_VALUE = 6;
    /**
     * <code>FindTrip = 7;</code>
     */
    public static final int FindTrip_VALUE = 7;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Type forNumber(int value) {
      switch (value) {
        case 0: return Unknown;
        case 1: return Login;
        case 2: return Logout;
        case 3: return FindSeats;
        case 4: return FindTrips;
        case 5: return MakeReservation;
        case 6: return FindEmployee;
        case 7: return FindTrip;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return transportAgency.protobufprotocol.Request.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:transportAgency.protobufprotocol.Request.Type)
  }

  private int payloadCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object payload_;
  public enum PayloadCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    TRIP(2),
    EMPLOYEE(3),
    RESERVATION(4),
    PAYLOAD_NOT_SET(0);
    private final int value;
    private PayloadCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PayloadCase valueOf(int value) {
      return forNumber(value);
    }

    public static PayloadCase forNumber(int value) {
      switch (value) {
        case 2: return TRIP;
        case 3: return EMPLOYEE;
        case 4: return RESERVATION;
        case 0: return PAYLOAD_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PayloadCase
  getPayloadCase() {
    return PayloadCase.forNumber(
        payloadCase_);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_ = 0;
  /**
   * <code>.transportAgency.protobufprotocol.Request.Type type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.transportAgency.protobufprotocol.Request.Type type = 1;</code>
   * @return The type.
   */
  @java.lang.Override public transportAgency.protobufprotocol.Request.Type getType() {
    transportAgency.protobufprotocol.Request.Type result = transportAgency.protobufprotocol.Request.Type.forNumber(type_);
    return result == null ? transportAgency.protobufprotocol.Request.Type.UNRECOGNIZED : result;
  }

  public static final int TRIP_FIELD_NUMBER = 2;
  /**
   * <code>.transportAgency.protobufprotocol.Trip trip = 2;</code>
   * @return Whether the trip field is set.
   */
  @java.lang.Override
  public boolean hasTrip() {
    return payloadCase_ == 2;
  }
  /**
   * <code>.transportAgency.protobufprotocol.Trip trip = 2;</code>
   * @return The trip.
   */
  @java.lang.Override
  public transportAgency.protobufprotocol.Trip getTrip() {
    if (payloadCase_ == 2) {
       return (transportAgency.protobufprotocol.Trip) payload_;
    }
    return transportAgency.protobufprotocol.Trip.getDefaultInstance();
  }
  /**
   * <code>.transportAgency.protobufprotocol.Trip trip = 2;</code>
   */
  @java.lang.Override
  public transportAgency.protobufprotocol.TripOrBuilder getTripOrBuilder() {
    if (payloadCase_ == 2) {
       return (transportAgency.protobufprotocol.Trip) payload_;
    }
    return transportAgency.protobufprotocol.Trip.getDefaultInstance();
  }

  public static final int EMPLOYEE_FIELD_NUMBER = 3;
  /**
   * <code>.transportAgency.protobufprotocol.Employee employee = 3;</code>
   * @return Whether the employee field is set.
   */
  @java.lang.Override
  public boolean hasEmployee() {
    return payloadCase_ == 3;
  }
  /**
   * <code>.transportAgency.protobufprotocol.Employee employee = 3;</code>
   * @return The employee.
   */
  @java.lang.Override
  public transportAgency.protobufprotocol.Employee getEmployee() {
    if (payloadCase_ == 3) {
       return (transportAgency.protobufprotocol.Employee) payload_;
    }
    return transportAgency.protobufprotocol.Employee.getDefaultInstance();
  }
  /**
   * <code>.transportAgency.protobufprotocol.Employee employee = 3;</code>
   */
  @java.lang.Override
  public transportAgency.protobufprotocol.EmployeeOrBuilder getEmployeeOrBuilder() {
    if (payloadCase_ == 3) {
       return (transportAgency.protobufprotocol.Employee) payload_;
    }
    return transportAgency.protobufprotocol.Employee.getDefaultInstance();
  }

  public static final int RESERVATION_FIELD_NUMBER = 4;
  /**
   * <code>.transportAgency.protobufprotocol.Reservation reservation = 4;</code>
   * @return Whether the reservation field is set.
   */
  @java.lang.Override
  public boolean hasReservation() {
    return payloadCase_ == 4;
  }
  /**
   * <code>.transportAgency.protobufprotocol.Reservation reservation = 4;</code>
   * @return The reservation.
   */
  @java.lang.Override
  public transportAgency.protobufprotocol.Reservation getReservation() {
    if (payloadCase_ == 4) {
       return (transportAgency.protobufprotocol.Reservation) payload_;
    }
    return transportAgency.protobufprotocol.Reservation.getDefaultInstance();
  }
  /**
   * <code>.transportAgency.protobufprotocol.Reservation reservation = 4;</code>
   */
  @java.lang.Override
  public transportAgency.protobufprotocol.ReservationOrBuilder getReservationOrBuilder() {
    if (payloadCase_ == 4) {
       return (transportAgency.protobufprotocol.Reservation) payload_;
    }
    return transportAgency.protobufprotocol.Reservation.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != transportAgency.protobufprotocol.Request.Type.Unknown.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (payloadCase_ == 2) {
      output.writeMessage(2, (transportAgency.protobufprotocol.Trip) payload_);
    }
    if (payloadCase_ == 3) {
      output.writeMessage(3, (transportAgency.protobufprotocol.Employee) payload_);
    }
    if (payloadCase_ == 4) {
      output.writeMessage(4, (transportAgency.protobufprotocol.Reservation) payload_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != transportAgency.protobufprotocol.Request.Type.Unknown.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (payloadCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (transportAgency.protobufprotocol.Trip) payload_);
    }
    if (payloadCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (transportAgency.protobufprotocol.Employee) payload_);
    }
    if (payloadCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (transportAgency.protobufprotocol.Reservation) payload_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof transportAgency.protobufprotocol.Request)) {
      return super.equals(obj);
    }
    transportAgency.protobufprotocol.Request other = (transportAgency.protobufprotocol.Request) obj;

    if (type_ != other.type_) return false;
    if (!getPayloadCase().equals(other.getPayloadCase())) return false;
    switch (payloadCase_) {
      case 2:
        if (!getTrip()
            .equals(other.getTrip())) return false;
        break;
      case 3:
        if (!getEmployee()
            .equals(other.getEmployee())) return false;
        break;
      case 4:
        if (!getReservation()
            .equals(other.getReservation())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    switch (payloadCase_) {
      case 2:
        hash = (37 * hash) + TRIP_FIELD_NUMBER;
        hash = (53 * hash) + getTrip().hashCode();
        break;
      case 3:
        hash = (37 * hash) + EMPLOYEE_FIELD_NUMBER;
        hash = (53 * hash) + getEmployee().hashCode();
        break;
      case 4:
        hash = (37 * hash) + RESERVATION_FIELD_NUMBER;
        hash = (53 * hash) + getReservation().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static transportAgency.protobufprotocol.Request parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static transportAgency.protobufprotocol.Request parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static transportAgency.protobufprotocol.Request parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static transportAgency.protobufprotocol.Request parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static transportAgency.protobufprotocol.Request parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static transportAgency.protobufprotocol.Request parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static transportAgency.protobufprotocol.Request parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static transportAgency.protobufprotocol.Request parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static transportAgency.protobufprotocol.Request parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static transportAgency.protobufprotocol.Request parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static transportAgency.protobufprotocol.Request parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static transportAgency.protobufprotocol.Request parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(transportAgency.protobufprotocol.Request prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code transportAgency.protobufprotocol.Request}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:transportAgency.protobufprotocol.Request)
      transportAgency.protobufprotocol.RequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return transportAgency.protobufprotocol.ProtoDefGenerated.internal_static_transportAgency_protobufprotocol_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return transportAgency.protobufprotocol.ProtoDefGenerated.internal_static_transportAgency_protobufprotocol_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              transportAgency.protobufprotocol.Request.class, transportAgency.protobufprotocol.Request.Builder.class);
    }

    // Construct using transportAgency.protobufprotocol.Request.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      type_ = 0;
      if (tripBuilder_ != null) {
        tripBuilder_.clear();
      }
      if (employeeBuilder_ != null) {
        employeeBuilder_.clear();
      }
      if (reservationBuilder_ != null) {
        reservationBuilder_.clear();
      }
      payloadCase_ = 0;
      payload_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return transportAgency.protobufprotocol.ProtoDefGenerated.internal_static_transportAgency_protobufprotocol_Request_descriptor;
    }

    @java.lang.Override
    public transportAgency.protobufprotocol.Request getDefaultInstanceForType() {
      return transportAgency.protobufprotocol.Request.getDefaultInstance();
    }

    @java.lang.Override
    public transportAgency.protobufprotocol.Request build() {
      transportAgency.protobufprotocol.Request result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public transportAgency.protobufprotocol.Request buildPartial() {
      transportAgency.protobufprotocol.Request result = new transportAgency.protobufprotocol.Request(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(transportAgency.protobufprotocol.Request result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.type_ = type_;
      }
    }

    private void buildPartialOneofs(transportAgency.protobufprotocol.Request result) {
      result.payloadCase_ = payloadCase_;
      result.payload_ = this.payload_;
      if (payloadCase_ == 2 &&
          tripBuilder_ != null) {
        result.payload_ = tripBuilder_.build();
      }
      if (payloadCase_ == 3 &&
          employeeBuilder_ != null) {
        result.payload_ = employeeBuilder_.build();
      }
      if (payloadCase_ == 4 &&
          reservationBuilder_ != null) {
        result.payload_ = reservationBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof transportAgency.protobufprotocol.Request) {
        return mergeFrom((transportAgency.protobufprotocol.Request)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(transportAgency.protobufprotocol.Request other) {
      if (other == transportAgency.protobufprotocol.Request.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      switch (other.getPayloadCase()) {
        case TRIP: {
          mergeTrip(other.getTrip());
          break;
        }
        case EMPLOYEE: {
          mergeEmployee(other.getEmployee());
          break;
        }
        case RESERVATION: {
          mergeReservation(other.getReservation());
          break;
        }
        case PAYLOAD_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  internalGetTripFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetEmployeeFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 3;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetReservationFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 4;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int payloadCase_ = 0;
    private java.lang.Object payload_;
    public PayloadCase
        getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public Builder clearPayload() {
      payloadCase_ = 0;
      payload_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private int type_ = 0;
    /**
     * <code>.transportAgency.protobufprotocol.Request.Type type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Request.Type type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Request.Type type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public transportAgency.protobufprotocol.Request.Type getType() {
      transportAgency.protobufprotocol.Request.Type result = transportAgency.protobufprotocol.Request.Type.forNumber(type_);
      return result == null ? transportAgency.protobufprotocol.Request.Type.UNRECOGNIZED : result;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Request.Type type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(transportAgency.protobufprotocol.Request.Type value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Request.Type type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilder<
        transportAgency.protobufprotocol.Trip, transportAgency.protobufprotocol.Trip.Builder, transportAgency.protobufprotocol.TripOrBuilder> tripBuilder_;
    /**
     * <code>.transportAgency.protobufprotocol.Trip trip = 2;</code>
     * @return Whether the trip field is set.
     */
    @java.lang.Override
    public boolean hasTrip() {
      return payloadCase_ == 2;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Trip trip = 2;</code>
     * @return The trip.
     */
    @java.lang.Override
    public transportAgency.protobufprotocol.Trip getTrip() {
      if (tripBuilder_ == null) {
        if (payloadCase_ == 2) {
          return (transportAgency.protobufprotocol.Trip) payload_;
        }
        return transportAgency.protobufprotocol.Trip.getDefaultInstance();
      } else {
        if (payloadCase_ == 2) {
          return tripBuilder_.getMessage();
        }
        return transportAgency.protobufprotocol.Trip.getDefaultInstance();
      }
    }
    /**
     * <code>.transportAgency.protobufprotocol.Trip trip = 2;</code>
     */
    public Builder setTrip(transportAgency.protobufprotocol.Trip value) {
      if (tripBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        tripBuilder_.setMessage(value);
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Trip trip = 2;</code>
     */
    public Builder setTrip(
        transportAgency.protobufprotocol.Trip.Builder builderForValue) {
      if (tripBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        tripBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Trip trip = 2;</code>
     */
    public Builder mergeTrip(transportAgency.protobufprotocol.Trip value) {
      if (tripBuilder_ == null) {
        if (payloadCase_ == 2 &&
            payload_ != transportAgency.protobufprotocol.Trip.getDefaultInstance()) {
          payload_ = transportAgency.protobufprotocol.Trip.newBuilder((transportAgency.protobufprotocol.Trip) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 2) {
          tripBuilder_.mergeFrom(value);
        } else {
          tripBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Trip trip = 2;</code>
     */
    public Builder clearTrip() {
      if (tripBuilder_ == null) {
        if (payloadCase_ == 2) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 2) {
          payloadCase_ = 0;
          payload_ = null;
        }
        tripBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Trip trip = 2;</code>
     */
    public transportAgency.protobufprotocol.Trip.Builder getTripBuilder() {
      return internalGetTripFieldBuilder().getBuilder();
    }
    /**
     * <code>.transportAgency.protobufprotocol.Trip trip = 2;</code>
     */
    @java.lang.Override
    public transportAgency.protobufprotocol.TripOrBuilder getTripOrBuilder() {
      if ((payloadCase_ == 2) && (tripBuilder_ != null)) {
        return tripBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 2) {
          return (transportAgency.protobufprotocol.Trip) payload_;
        }
        return transportAgency.protobufprotocol.Trip.getDefaultInstance();
      }
    }
    /**
     * <code>.transportAgency.protobufprotocol.Trip trip = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        transportAgency.protobufprotocol.Trip, transportAgency.protobufprotocol.Trip.Builder, transportAgency.protobufprotocol.TripOrBuilder> 
        internalGetTripFieldBuilder() {
      if (tripBuilder_ == null) {
        if (!(payloadCase_ == 2)) {
          payload_ = transportAgency.protobufprotocol.Trip.getDefaultInstance();
        }
        tripBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            transportAgency.protobufprotocol.Trip, transportAgency.protobufprotocol.Trip.Builder, transportAgency.protobufprotocol.TripOrBuilder>(
                (transportAgency.protobufprotocol.Trip) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 2;
      onChanged();
      return tripBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        transportAgency.protobufprotocol.Employee, transportAgency.protobufprotocol.Employee.Builder, transportAgency.protobufprotocol.EmployeeOrBuilder> employeeBuilder_;
    /**
     * <code>.transportAgency.protobufprotocol.Employee employee = 3;</code>
     * @return Whether the employee field is set.
     */
    @java.lang.Override
    public boolean hasEmployee() {
      return payloadCase_ == 3;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Employee employee = 3;</code>
     * @return The employee.
     */
    @java.lang.Override
    public transportAgency.protobufprotocol.Employee getEmployee() {
      if (employeeBuilder_ == null) {
        if (payloadCase_ == 3) {
          return (transportAgency.protobufprotocol.Employee) payload_;
        }
        return transportAgency.protobufprotocol.Employee.getDefaultInstance();
      } else {
        if (payloadCase_ == 3) {
          return employeeBuilder_.getMessage();
        }
        return transportAgency.protobufprotocol.Employee.getDefaultInstance();
      }
    }
    /**
     * <code>.transportAgency.protobufprotocol.Employee employee = 3;</code>
     */
    public Builder setEmployee(transportAgency.protobufprotocol.Employee value) {
      if (employeeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        employeeBuilder_.setMessage(value);
      }
      payloadCase_ = 3;
      return this;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Employee employee = 3;</code>
     */
    public Builder setEmployee(
        transportAgency.protobufprotocol.Employee.Builder builderForValue) {
      if (employeeBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        employeeBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 3;
      return this;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Employee employee = 3;</code>
     */
    public Builder mergeEmployee(transportAgency.protobufprotocol.Employee value) {
      if (employeeBuilder_ == null) {
        if (payloadCase_ == 3 &&
            payload_ != transportAgency.protobufprotocol.Employee.getDefaultInstance()) {
          payload_ = transportAgency.protobufprotocol.Employee.newBuilder((transportAgency.protobufprotocol.Employee) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 3) {
          employeeBuilder_.mergeFrom(value);
        } else {
          employeeBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 3;
      return this;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Employee employee = 3;</code>
     */
    public Builder clearEmployee() {
      if (employeeBuilder_ == null) {
        if (payloadCase_ == 3) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 3) {
          payloadCase_ = 0;
          payload_ = null;
        }
        employeeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Employee employee = 3;</code>
     */
    public transportAgency.protobufprotocol.Employee.Builder getEmployeeBuilder() {
      return internalGetEmployeeFieldBuilder().getBuilder();
    }
    /**
     * <code>.transportAgency.protobufprotocol.Employee employee = 3;</code>
     */
    @java.lang.Override
    public transportAgency.protobufprotocol.EmployeeOrBuilder getEmployeeOrBuilder() {
      if ((payloadCase_ == 3) && (employeeBuilder_ != null)) {
        return employeeBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 3) {
          return (transportAgency.protobufprotocol.Employee) payload_;
        }
        return transportAgency.protobufprotocol.Employee.getDefaultInstance();
      }
    }
    /**
     * <code>.transportAgency.protobufprotocol.Employee employee = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        transportAgency.protobufprotocol.Employee, transportAgency.protobufprotocol.Employee.Builder, transportAgency.protobufprotocol.EmployeeOrBuilder> 
        internalGetEmployeeFieldBuilder() {
      if (employeeBuilder_ == null) {
        if (!(payloadCase_ == 3)) {
          payload_ = transportAgency.protobufprotocol.Employee.getDefaultInstance();
        }
        employeeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            transportAgency.protobufprotocol.Employee, transportAgency.protobufprotocol.Employee.Builder, transportAgency.protobufprotocol.EmployeeOrBuilder>(
                (transportAgency.protobufprotocol.Employee) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 3;
      onChanged();
      return employeeBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        transportAgency.protobufprotocol.Reservation, transportAgency.protobufprotocol.Reservation.Builder, transportAgency.protobufprotocol.ReservationOrBuilder> reservationBuilder_;
    /**
     * <code>.transportAgency.protobufprotocol.Reservation reservation = 4;</code>
     * @return Whether the reservation field is set.
     */
    @java.lang.Override
    public boolean hasReservation() {
      return payloadCase_ == 4;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Reservation reservation = 4;</code>
     * @return The reservation.
     */
    @java.lang.Override
    public transportAgency.protobufprotocol.Reservation getReservation() {
      if (reservationBuilder_ == null) {
        if (payloadCase_ == 4) {
          return (transportAgency.protobufprotocol.Reservation) payload_;
        }
        return transportAgency.protobufprotocol.Reservation.getDefaultInstance();
      } else {
        if (payloadCase_ == 4) {
          return reservationBuilder_.getMessage();
        }
        return transportAgency.protobufprotocol.Reservation.getDefaultInstance();
      }
    }
    /**
     * <code>.transportAgency.protobufprotocol.Reservation reservation = 4;</code>
     */
    public Builder setReservation(transportAgency.protobufprotocol.Reservation value) {
      if (reservationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        reservationBuilder_.setMessage(value);
      }
      payloadCase_ = 4;
      return this;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Reservation reservation = 4;</code>
     */
    public Builder setReservation(
        transportAgency.protobufprotocol.Reservation.Builder builderForValue) {
      if (reservationBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        reservationBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 4;
      return this;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Reservation reservation = 4;</code>
     */
    public Builder mergeReservation(transportAgency.protobufprotocol.Reservation value) {
      if (reservationBuilder_ == null) {
        if (payloadCase_ == 4 &&
            payload_ != transportAgency.protobufprotocol.Reservation.getDefaultInstance()) {
          payload_ = transportAgency.protobufprotocol.Reservation.newBuilder((transportAgency.protobufprotocol.Reservation) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 4) {
          reservationBuilder_.mergeFrom(value);
        } else {
          reservationBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 4;
      return this;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Reservation reservation = 4;</code>
     */
    public Builder clearReservation() {
      if (reservationBuilder_ == null) {
        if (payloadCase_ == 4) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 4) {
          payloadCase_ = 0;
          payload_ = null;
        }
        reservationBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Reservation reservation = 4;</code>
     */
    public transportAgency.protobufprotocol.Reservation.Builder getReservationBuilder() {
      return internalGetReservationFieldBuilder().getBuilder();
    }
    /**
     * <code>.transportAgency.protobufprotocol.Reservation reservation = 4;</code>
     */
    @java.lang.Override
    public transportAgency.protobufprotocol.ReservationOrBuilder getReservationOrBuilder() {
      if ((payloadCase_ == 4) && (reservationBuilder_ != null)) {
        return reservationBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 4) {
          return (transportAgency.protobufprotocol.Reservation) payload_;
        }
        return transportAgency.protobufprotocol.Reservation.getDefaultInstance();
      }
    }
    /**
     * <code>.transportAgency.protobufprotocol.Reservation reservation = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        transportAgency.protobufprotocol.Reservation, transportAgency.protobufprotocol.Reservation.Builder, transportAgency.protobufprotocol.ReservationOrBuilder> 
        internalGetReservationFieldBuilder() {
      if (reservationBuilder_ == null) {
        if (!(payloadCase_ == 4)) {
          payload_ = transportAgency.protobufprotocol.Reservation.getDefaultInstance();
        }
        reservationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            transportAgency.protobufprotocol.Reservation, transportAgency.protobufprotocol.Reservation.Builder, transportAgency.protobufprotocol.ReservationOrBuilder>(
                (transportAgency.protobufprotocol.Reservation) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 4;
      onChanged();
      return reservationBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:transportAgency.protobufprotocol.Request)
  }

  // @@protoc_insertion_point(class_scope:transportAgency.protobufprotocol.Request)
  private static final transportAgency.protobufprotocol.Request DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new transportAgency.protobufprotocol.Request();
  }

  public static transportAgency.protobufprotocol.Request getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Request>
      PARSER = new com.google.protobuf.AbstractParser<Request>() {
    @java.lang.Override
    public Request parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Request> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Request> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public transportAgency.protobufprotocol.Request getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

