// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ProtoDef.proto
// Protobuf Java Version: 4.30.2

package transportAgency.protobufprotocol;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transportAgency.protobufprotocol.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.transportAgency.protobufprotocol.Request.Type type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.transportAgency.protobufprotocol.Request.Type type = 1;</code>
   * @return The type.
   */
  transportAgency.protobufprotocol.Request.Type getType();

  /**
   * <code>.transportAgency.protobufprotocol.Trip trip = 2;</code>
   * @return Whether the trip field is set.
   */
  boolean hasTrip();
  /**
   * <code>.transportAgency.protobufprotocol.Trip trip = 2;</code>
   * @return The trip.
   */
  transportAgency.protobufprotocol.Trip getTrip();
  /**
   * <code>.transportAgency.protobufprotocol.Trip trip = 2;</code>
   */
  transportAgency.protobufprotocol.TripOrBuilder getTripOrBuilder();

  /**
   * <code>.transportAgency.protobufprotocol.Employee employee = 3;</code>
   * @return Whether the employee field is set.
   */
  boolean hasEmployee();
  /**
   * <code>.transportAgency.protobufprotocol.Employee employee = 3;</code>
   * @return The employee.
   */
  transportAgency.protobufprotocol.Employee getEmployee();
  /**
   * <code>.transportAgency.protobufprotocol.Employee employee = 3;</code>
   */
  transportAgency.protobufprotocol.EmployeeOrBuilder getEmployeeOrBuilder();

  /**
   * <code>.transportAgency.protobufprotocol.Reservation reservation = 4;</code>
   * @return Whether the reservation field is set.
   */
  boolean hasReservation();
  /**
   * <code>.transportAgency.protobufprotocol.Reservation reservation = 4;</code>
   * @return The reservation.
   */
  transportAgency.protobufprotocol.Reservation getReservation();
  /**
   * <code>.transportAgency.protobufprotocol.Reservation reservation = 4;</code>
   */
  transportAgency.protobufprotocol.ReservationOrBuilder getReservationOrBuilder();

  transportAgency.protobufprotocol.Request.PayloadCase getPayloadCase();
}
