// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ProtoDef.proto
// Protobuf Java Version: 4.30.2

package transportAgency.protobufprotocol;

/**
 * Protobuf type {@code transportAgency.protobufprotocol.Reservation}
 */
public final class Reservation extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:transportAgency.protobufprotocol.Reservation)
    ReservationOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      Reservation.class.getName());
  }
  // Use Reservation.newBuilder() to construct.
  private Reservation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Reservation() {
    clientName_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return transportAgency.protobufprotocol.ProtoDefGenerated.internal_static_transportAgency_protobufprotocol_Reservation_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return transportAgency.protobufprotocol.ProtoDefGenerated.internal_static_transportAgency_protobufprotocol_Reservation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            transportAgency.protobufprotocol.Reservation.class, transportAgency.protobufprotocol.Reservation.Builder.class);
  }

  private int bitField0_;
  public static final int CLIENTNAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object clientName_ = "";
  /**
   * <code>string clientName = 1;</code>
   * @return The clientName.
   */
  @java.lang.Override
  public java.lang.String getClientName() {
    java.lang.Object ref = clientName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientName_ = s;
      return s;
    }
  }
  /**
   * <code>string clientName = 1;</code>
   * @return The bytes for clientName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClientNameBytes() {
    java.lang.Object ref = clientName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOSEATS_FIELD_NUMBER = 2;
  private int noSeats_ = 0;
  /**
   * <code>int32 noSeats = 2;</code>
   * @return The noSeats.
   */
  @java.lang.Override
  public int getNoSeats() {
    return noSeats_;
  }

  public static final int TRIP_FIELD_NUMBER = 3;
  private transportAgency.protobufprotocol.Trip trip_;
  /**
   * <code>.transportAgency.protobufprotocol.Trip trip = 3;</code>
   * @return Whether the trip field is set.
   */
  @java.lang.Override
  public boolean hasTrip() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.transportAgency.protobufprotocol.Trip trip = 3;</code>
   * @return The trip.
   */
  @java.lang.Override
  public transportAgency.protobufprotocol.Trip getTrip() {
    return trip_ == null ? transportAgency.protobufprotocol.Trip.getDefaultInstance() : trip_;
  }
  /**
   * <code>.transportAgency.protobufprotocol.Trip trip = 3;</code>
   */
  @java.lang.Override
  public transportAgency.protobufprotocol.TripOrBuilder getTripOrBuilder() {
    return trip_ == null ? transportAgency.protobufprotocol.Trip.getDefaultInstance() : trip_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(clientName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, clientName_);
    }
    if (noSeats_ != 0) {
      output.writeInt32(2, noSeats_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getTrip());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(clientName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, clientName_);
    }
    if (noSeats_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, noSeats_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getTrip());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof transportAgency.protobufprotocol.Reservation)) {
      return super.equals(obj);
    }
    transportAgency.protobufprotocol.Reservation other = (transportAgency.protobufprotocol.Reservation) obj;

    if (!getClientName()
        .equals(other.getClientName())) return false;
    if (getNoSeats()
        != other.getNoSeats()) return false;
    if (hasTrip() != other.hasTrip()) return false;
    if (hasTrip()) {
      if (!getTrip()
          .equals(other.getTrip())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLIENTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getClientName().hashCode();
    hash = (37 * hash) + NOSEATS_FIELD_NUMBER;
    hash = (53 * hash) + getNoSeats();
    if (hasTrip()) {
      hash = (37 * hash) + TRIP_FIELD_NUMBER;
      hash = (53 * hash) + getTrip().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static transportAgency.protobufprotocol.Reservation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static transportAgency.protobufprotocol.Reservation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static transportAgency.protobufprotocol.Reservation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static transportAgency.protobufprotocol.Reservation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static transportAgency.protobufprotocol.Reservation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static transportAgency.protobufprotocol.Reservation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static transportAgency.protobufprotocol.Reservation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static transportAgency.protobufprotocol.Reservation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static transportAgency.protobufprotocol.Reservation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static transportAgency.protobufprotocol.Reservation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static transportAgency.protobufprotocol.Reservation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static transportAgency.protobufprotocol.Reservation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(transportAgency.protobufprotocol.Reservation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code transportAgency.protobufprotocol.Reservation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:transportAgency.protobufprotocol.Reservation)
      transportAgency.protobufprotocol.ReservationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return transportAgency.protobufprotocol.ProtoDefGenerated.internal_static_transportAgency_protobufprotocol_Reservation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return transportAgency.protobufprotocol.ProtoDefGenerated.internal_static_transportAgency_protobufprotocol_Reservation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              transportAgency.protobufprotocol.Reservation.class, transportAgency.protobufprotocol.Reservation.Builder.class);
    }

    // Construct using transportAgency.protobufprotocol.Reservation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetTripFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      clientName_ = "";
      noSeats_ = 0;
      trip_ = null;
      if (tripBuilder_ != null) {
        tripBuilder_.dispose();
        tripBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return transportAgency.protobufprotocol.ProtoDefGenerated.internal_static_transportAgency_protobufprotocol_Reservation_descriptor;
    }

    @java.lang.Override
    public transportAgency.protobufprotocol.Reservation getDefaultInstanceForType() {
      return transportAgency.protobufprotocol.Reservation.getDefaultInstance();
    }

    @java.lang.Override
    public transportAgency.protobufprotocol.Reservation build() {
      transportAgency.protobufprotocol.Reservation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public transportAgency.protobufprotocol.Reservation buildPartial() {
      transportAgency.protobufprotocol.Reservation result = new transportAgency.protobufprotocol.Reservation(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(transportAgency.protobufprotocol.Reservation result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.clientName_ = clientName_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.noSeats_ = noSeats_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.trip_ = tripBuilder_ == null
            ? trip_
            : tripBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof transportAgency.protobufprotocol.Reservation) {
        return mergeFrom((transportAgency.protobufprotocol.Reservation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(transportAgency.protobufprotocol.Reservation other) {
      if (other == transportAgency.protobufprotocol.Reservation.getDefaultInstance()) return this;
      if (!other.getClientName().isEmpty()) {
        clientName_ = other.clientName_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getNoSeats() != 0) {
        setNoSeats(other.getNoSeats());
      }
      if (other.hasTrip()) {
        mergeTrip(other.getTrip());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              clientName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              noSeats_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  internalGetTripFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object clientName_ = "";
    /**
     * <code>string clientName = 1;</code>
     * @return The clientName.
     */
    public java.lang.String getClientName() {
      java.lang.Object ref = clientName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string clientName = 1;</code>
     * @return The bytes for clientName.
     */
    public com.google.protobuf.ByteString
        getClientNameBytes() {
      java.lang.Object ref = clientName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string clientName = 1;</code>
     * @param value The clientName to set.
     * @return This builder for chaining.
     */
    public Builder setClientName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      clientName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string clientName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientName() {
      clientName_ = getDefaultInstance().getClientName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string clientName = 1;</code>
     * @param value The bytes for clientName to set.
     * @return This builder for chaining.
     */
    public Builder setClientNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      clientName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int noSeats_ ;
    /**
     * <code>int32 noSeats = 2;</code>
     * @return The noSeats.
     */
    @java.lang.Override
    public int getNoSeats() {
      return noSeats_;
    }
    /**
     * <code>int32 noSeats = 2;</code>
     * @param value The noSeats to set.
     * @return This builder for chaining.
     */
    public Builder setNoSeats(int value) {

      noSeats_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 noSeats = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNoSeats() {
      bitField0_ = (bitField0_ & ~0x00000002);
      noSeats_ = 0;
      onChanged();
      return this;
    }

    private transportAgency.protobufprotocol.Trip trip_;
    private com.google.protobuf.SingleFieldBuilder<
        transportAgency.protobufprotocol.Trip, transportAgency.protobufprotocol.Trip.Builder, transportAgency.protobufprotocol.TripOrBuilder> tripBuilder_;
    /**
     * <code>.transportAgency.protobufprotocol.Trip trip = 3;</code>
     * @return Whether the trip field is set.
     */
    public boolean hasTrip() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.transportAgency.protobufprotocol.Trip trip = 3;</code>
     * @return The trip.
     */
    public transportAgency.protobufprotocol.Trip getTrip() {
      if (tripBuilder_ == null) {
        return trip_ == null ? transportAgency.protobufprotocol.Trip.getDefaultInstance() : trip_;
      } else {
        return tripBuilder_.getMessage();
      }
    }
    /**
     * <code>.transportAgency.protobufprotocol.Trip trip = 3;</code>
     */
    public Builder setTrip(transportAgency.protobufprotocol.Trip value) {
      if (tripBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        trip_ = value;
      } else {
        tripBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Trip trip = 3;</code>
     */
    public Builder setTrip(
        transportAgency.protobufprotocol.Trip.Builder builderForValue) {
      if (tripBuilder_ == null) {
        trip_ = builderForValue.build();
      } else {
        tripBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Trip trip = 3;</code>
     */
    public Builder mergeTrip(transportAgency.protobufprotocol.Trip value) {
      if (tripBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          trip_ != null &&
          trip_ != transportAgency.protobufprotocol.Trip.getDefaultInstance()) {
          getTripBuilder().mergeFrom(value);
        } else {
          trip_ = value;
        }
      } else {
        tripBuilder_.mergeFrom(value);
      }
      if (trip_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Trip trip = 3;</code>
     */
    public Builder clearTrip() {
      bitField0_ = (bitField0_ & ~0x00000004);
      trip_ = null;
      if (tripBuilder_ != null) {
        tripBuilder_.dispose();
        tripBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.transportAgency.protobufprotocol.Trip trip = 3;</code>
     */
    public transportAgency.protobufprotocol.Trip.Builder getTripBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetTripFieldBuilder().getBuilder();
    }
    /**
     * <code>.transportAgency.protobufprotocol.Trip trip = 3;</code>
     */
    public transportAgency.protobufprotocol.TripOrBuilder getTripOrBuilder() {
      if (tripBuilder_ != null) {
        return tripBuilder_.getMessageOrBuilder();
      } else {
        return trip_ == null ?
            transportAgency.protobufprotocol.Trip.getDefaultInstance() : trip_;
      }
    }
    /**
     * <code>.transportAgency.protobufprotocol.Trip trip = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        transportAgency.protobufprotocol.Trip, transportAgency.protobufprotocol.Trip.Builder, transportAgency.protobufprotocol.TripOrBuilder> 
        internalGetTripFieldBuilder() {
      if (tripBuilder_ == null) {
        tripBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            transportAgency.protobufprotocol.Trip, transportAgency.protobufprotocol.Trip.Builder, transportAgency.protobufprotocol.TripOrBuilder>(
                getTrip(),
                getParentForChildren(),
                isClean());
        trip_ = null;
      }
      return tripBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:transportAgency.protobufprotocol.Reservation)
  }

  // @@protoc_insertion_point(class_scope:transportAgency.protobufprotocol.Reservation)
  private static final transportAgency.protobufprotocol.Reservation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new transportAgency.protobufprotocol.Reservation();
  }

  public static transportAgency.protobufprotocol.Reservation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Reservation>
      PARSER = new com.google.protobuf.AbstractParser<Reservation>() {
    @java.lang.Override
    public Reservation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Reservation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Reservation> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public transportAgency.protobufprotocol.Reservation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

